### ISSUE TITLE
"There is no "public" asset package." when saving record with article

### ISSUE THREAD

**Issue by I-Valchev** [bolt/article#1]
![image](https://user-images.githubusercontent.com/7093518/91031053-55143e80-e600-11ea-9d2b-483ed69a4e82.png)

Seems related to https://github.com/bolt/article/commit/24f0c490236c7a5f053738e6a5a088e101a41a8a#diff-39e588c08d783fac977c2a962a821702L1-L7

**Comment by bobdenotter** [comment]
Fixed in `1.0.8` 😇
